version: "3"
services: 
  api:
    image: filipecabral/api-ts
    ports:
      - "6000:3050"
    links:
      - link-db
  link-db:
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no